import { pgTable, uuid, text, timestamp, integer, bigint, boolean, jsonb, inet, pgEnum } from 'drizzle-orm/pg-core';

const tenantStatusEnum = pgEnum('tenant_status_enum', ['pending', 'active', 'suspended', 'rejected', 'deleted']);
const customerStatusEnum = pgEnum('customer_status_enum', ['active', 'suspended', 'deleted']);
const userStatusEnum = pgEnum('user_status_enum', ['pending', 'active', 'disabled', 'locked']);
const portalEnum = pgEnum('portal_enum', ['provider', 'customer']);
const userRoleEnum = pgEnum('user_role_enum', [
  'ProviderOwner', 'ProviderAdmin', 'ProviderEngineer', 'ProviderViewer', 'ProviderBilling',
  'CustomerAdmin', 'CustomerDeveloper', 'CustomerViewer', 'SystemBot',
]);

export const tenants = pgTable('tenants', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  plan: text('plan').notNull().default('starter'),
  status: tenantStatusEnum('status').notNull().default('pending'),
  whiteLabel: jsonb('white_label'),
  applicationPayload: jsonb('application_payload').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  customerId: uuid('customer_id'),
  portal: portalEnum('portal').notNull(),
  email: text('email').notNull(),
  passwordHash: text('password_hash').notNull(),
  fullName: text('full_name'),
  role: userRoleEnum('role').notNull(),
  status: userStatusEnum('status').notNull().default('pending'),
  mfaEnabled: boolean('mfa_enabled').notNull().default(false),
  mfaSecretCiphertext: text('mfa_secret_ciphertext'),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  failedLoginCount: integer('failed_login_count').notNull().default(0),
  lockedUntil: timestamp('locked_until', { withTimezone: true }),
  notificationPrefs: jsonb('notification_prefs').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const sessions = pgTable('sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  tenantId: uuid('tenant_id').notNull(),
  refreshTokenHash: text('refresh_token_hash'),
  userAgent: text('user_agent'),
  ipAddress: inet('ip_address'),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const invites = pgTable('invites', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  customerId: uuid('customer_id'),
  email: text('email').notNull(),
  role: userRoleEnum('role').notNull(),
  tokenHash: text('token_hash').notNull().unique(),
  invitedBy: uuid('invited_by').notNull().references(() => users.id),
  status: text('status').notNull().default('pending'),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  acceptedAt: timestamp('accepted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const customers = pgTable('customers', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  industry: text('industry'),
  slaTier: text('sla_tier').notNull().default('standard'),
  status: customerStatusEnum('status').notNull().default('active'),
  contactEmail: text('contact_email'),
  contactPhone: text('contact_phone'),
  billingAccountId: uuid('billing_account_id'),
  whiteLabel: jsonb('white_label'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const contacts = pgTable('contacts', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull().references(() => customers.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  role: text('role').notNull().default('other'),
  email: text('email').notNull(),
  phone: text('phone'),
  isPrimary: boolean('is_primary').notNull().default(false),
  notificationPreference: jsonb('notification_preference').notNull().default({}),
  invitedAt: timestamp('invited_at', { withTimezone: true }),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  userId: uuid('user_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const projects = pgTable('projects', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  description: text('description'),
  status: text('status').notNull().default('configuring'),
  slaTier: text('sla_tier').notNull().default('standard'),
  defaultBranch: text('default_branch'),
  branchPolicy: jsonb('branch_policy'),
  dataRetentionDays: integer('data_retention_days').notNull().default(90),
  ownerUserId: uuid('owner_user_id').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const sources = pgTable('sources', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').notNull().unique().references(() => projects.id, { onDelete: 'cascade' }),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  sourceType: text('source_type').notNull(),
  repoFullName: text('repo_full_name'),
  repoUrl: text('repo_url'),
  branch: text('branch'),
  webhookId: text('webhook_id'),
  accessTokenCiphertext: text('access_token_ciphertext'),
  refreshTokenCiphertext: text('refresh_token_ciphertext'),
  tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),
  status: text('status').notNull().default('active'),
  lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const sourceSyncHistory = pgTable('source_sync_history', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  sourceId: uuid('source_id').notNull().references(() => sources.id, { onDelete: 'cascade' }),
  triggerType: text('trigger_type').notNull(),
  status: text('status').notNull(),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  durationMs: integer('duration_ms'),
  commitSha: text('commit_sha'),
  branch: text('branch'),
  fileCount: integer('file_count'),
  totalSizeBytes: bigint('total_size_bytes', { mode: 'number' }),
  assetHash: text('asset_hash'),
  snapshotId: uuid('snapshot_id'),
  errorCode: text('error_code'),
  errorMessage: text('error_message'),
  metadata: jsonb('metadata').notNull().default({}),
});

export const apiKeys = pgTable('api_keys', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  keyPrefix: text('key_prefix').notNull().unique(),
  keyHash: text('key_hash').notNull(),
  scopes: jsonb('scopes').notNull().default([]),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  lastUsedIp: inet('last_used_ip'),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  revokedBy: uuid('revoked_by'),
});

export const passwordResetTokens = pgTable('password_reset_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  tokenHash: text('token_hash').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  ipAddress: inet('ip_address'),
  userAgent: text('user_agent'),
  requestedVia: text('requested_via').notNull().default('web_form'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const engines = pgTable('engines', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id'),
  name: text('name').notNull(),
  engineType: text('engine_type').notNull(),
  version: text('version').notNull(),
  config: jsonb('config').notNull().default({}),
  enabled: boolean('enabled').notNull().default(true),
  healthStatus: text('health_status').notNull().default('unknown'),
  lastHealthCheckAt: timestamp('last_health_check_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const engineHealthChecks = pgTable('engine_health_checks', {
  id: uuid('id').primaryKey().defaultRandom(),
  engineId: uuid('engine_id').notNull().references(() => engines.id, { onDelete: 'cascade' }),
  tenantId: uuid('tenant_id'),
  healthStatus: text('health_status').notNull(),
  latencyMs: integer('latency_ms'),
  checkPayload: jsonb('check_payload').notNull().default({}),
  errorMessage: text('error_message'),
  checkedAt: timestamp('checked_at', { withTimezone: true }).notNull().defaultNow(),
});

export const rules = pgTable('rules', {
  id: uuid('id').primaryKey().defaultRandom(),
  engineId: uuid('engine_id').notNull().references(() => engines.id),
  ruleExternalId: text('rule_external_id').notNull(),
  title: text('title').notNull(),
  description: text('description'),
  cweIds: jsonb('cwe_ids').notNull().default([]),
  owaspIds: jsonb('owasp_ids').notNull().default([]),
  severity: text('severity').notNull(),
  defaultEnabled: boolean('default_enabled').notNull().default(true),
  ruleMetadata: jsonb('rule_metadata').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const policyConfigs = pgTable('policy_configs', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  scope: text('scope').notNull(),
  customerId: uuid('customer_id').references(() => customers.id),
  projectId: uuid('project_id').references(() => projects.id),
  name: text('name').notNull(),
  enabledEngines: jsonb('enabled_engines').notNull().default([]),
  enabledRules: jsonb('enabled_rules').notNull().default([]),
  severityThreshold: text('severity_threshold').notNull().default('low'),
  incrementalMode: text('incremental_mode').notNull().default('call_graph'),
  autoScanOnSync: boolean('auto_scan_on_sync').notNull().default(false),
  scanScheduleCron: text('scan_schedule_cron'),
  includePaths: jsonb('include_paths').notNull().default([]),
  excludePaths: jsonb('exclude_paths').notNull().default([]),
  isDefault: boolean('is_default').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const policyVersions = pgTable('policy_versions', {
  id: uuid('id').primaryKey().defaultRandom(),
  policyId: uuid('policy_id').notNull().references(() => policyConfigs.id),
  snapshot: jsonb('snapshot').notNull(),
  changedBy: uuid('changed_by').notNull().references(() => users.id),
  changeNote: text('change_note'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const snapshots = pgTable('snapshots', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  branch: text('branch').notNull(),
  commitSha: text('commit_sha').notNull(),
  assetHash: text('asset_hash').notNull(),
  fileCount: integer('file_count').notNull(),
  totalSizeBytes: bigint('total_size_bytes', { mode: 'number' }).notNull(),
  languageStats: jsonb('language_stats').notNull().default({}),
  frameworkStats: jsonb('framework_stats').notNull().default({}),
  dependencyList: jsonb('dependency_list').notNull().default({}),
  callGraphRef: text('call_graph_ref'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const scanRuns = pgTable('scan_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').notNull().references(() => projects.id),
  snapshotId: uuid('snapshot_id').notNull().references(() => snapshots.id),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  policyVersionId: uuid('policy_version_id').references(() => policyVersions.id),
  triggerType: text('trigger_type').notNull(),
  triggeredBy: uuid('triggered_by').references(() => users.id),
  incrementalMode: text('incremental_mode').notNull(),
  status: text('status').notNull().default('queued'),
  startedAt: timestamp('started_at', { withTimezone: true }),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  durationMs: integer('duration_ms'),
  findingsTotal: integer('findings_total').notNull().default(0),
  findingsNew: integer('findings_new').notNull().default(0),
  findingsFixed: integer('findings_fixed').notNull().default(0),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const scanRunEngines = pgTable('scan_run_engines', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  scanRunId: uuid('scan_run_id').notNull().references(() => scanRuns.id, { onDelete: 'cascade' }),
  engineId: uuid('engine_id').notNull().references(() => engines.id),
  status: text('status').notNull(),
  startedAt: timestamp('started_at', { withTimezone: true }),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  durationMs: integer('duration_ms'),
  findingsCount: integer('findings_count').notNull().default(0),
  rulesExecuted: integer('rules_executed'),
  filesAnalyzed: integer('files_analyzed'),
  bytesAnalyzed: bigint('bytes_analyzed', { mode: 'number' }),
  retryCount: integer('retry_count').notNull().default(0),
  errorCode: text('error_code'),
  errorMessage: text('error_message'),
  rawOutputUri: text('raw_output_uri'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const findings = pgTable('findings', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  projectId: uuid('project_id').notNull().references(() => projects.id),
  scanRunId: uuid('scan_run_id').notNull().references(() => scanRuns.id),
  snapshotId: uuid('snapshot_id').notNull().references(() => snapshots.id),
  ruleId: uuid('rule_id').notNull().references(() => rules.id),
  fingerprint: text('fingerprint').notNull(),
  severity: text('severity').notNull(),
  status: text('status').notNull().default('open'),
  title: text('title').notNull(),
  description: text('description'),
  filePath: text('file_path').notNull().default(''),
  startLine: integer('start_line').notNull().default(0),
  endLine: integer('end_line').notNull().default(0),
  codeSnippet: text('code_snippet'),
  cweIds: jsonb('cwe_ids').notNull().default([]),
  owaspIds: jsonb('owasp_ids').notNull().default([]),
  confidence: text('confidence').notNull().default('medium'),
  engines: jsonb('engines').notNull().default([]),
  dfgPath: jsonb('dfg_path'),
  aiTriageHint: boolean('ai_triage_hint'),
  aiTriageScore: text('ai_triage_score'),
  confirmedBy: uuid('confirmed_by').references(() => users.id),
  confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
  assignedTo: uuid('assigned_to').references(() => users.id),
  ticketRef: jsonb('ticket_ref'),
  firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
  fixedAt: timestamp('fixed_at', { withTimezone: true }),
  closedAt: timestamp('closed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const findingStateHistory = pgTable('finding_state_history', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  findingId: uuid('finding_id').notNull().references(() => findings.id, { onDelete: 'cascade' }),
  fromStatus: text('from_status'),
  toStatus: text('to_status').notNull(),
  changeSource: text('change_source').notNull(),
  changedBy: uuid('changed_by'),
  reason: text('reason'),
  metadata: jsonb('metadata').notNull().default({}),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
});

export const findingComments = pgTable('finding_comments', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  findingId: uuid('finding_id').notNull().references(() => findings.id, { onDelete: 'cascade' }),
  authorUserId: uuid('author_user_id').notNull().references(() => users.id),
  body: text('body').notNull(),
  commentType: text('comment_type').notNull().default('note'),
  mentionedUserIds: jsonb('mentioned_user_ids').notNull().default([]),
  attachments: jsonb('attachments').notNull().default([]),
  isEdited: boolean('is_edited').notNull().default(false),
  editedAt: timestamp('edited_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const prScanChecks = pgTable('pr_scan_checks', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  projectId: uuid('project_id').notNull().references(() => projects.id),
  scanRunId: uuid('scan_run_id').notNull().references(() => scanRuns.id, { onDelete: 'cascade' }),
  sourceType: text('source_type').notNull(),
  externalId: text('external_id').notNull(),
  externalNodeId: text('external_node_id'),
  repoFullName: text('repo_full_name').notNull(),
  ref: text('ref').notNull(),
  headSha: text('head_sha').notNull(),
  baseSha: text('base_sha').notNull(),
  status: text('status').notNull(),
  conclusion: text('conclusion'),
  blocking: boolean('blocking').notNull().default(false),
  blockingThreshold: text('blocking_threshold'),
  externalCheckRunId: text('external_check_run_id'),
  externalCheckUrl: text('external_check_url'),
  startedAt: timestamp('started_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const pocRuns = pgTable('poc_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  projectId: uuid('project_id').notNull().references(() => projects.id),
  findingId: uuid('finding_id').notNull().references(() => findings.id),
  source: text('source').notNull(),
  pocLibraryId: uuid('poc_library_id'),
  pocScript: text('poc_script').notNull(),
  pocScriptHash: text('poc_script_hash').notNull(),
  status: text('status').notNull().default('pending'),
  approvedBy: uuid('approved_by').references(() => users.id),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  startedAt: timestamp('started_at', { withTimezone: true }),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  durationMs: integer('duration_ms'),
  exploitProven: boolean('exploit_proven').notNull().default(false),
  exitCode: integer('exit_code'),
  stdoutLog: text('stdout_log'),
  stderrLog: text('stderr_log'),
  behaviorReport: jsonb('behavior_report'),
  evidenceUrl: text('evidence_url'),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const pocSandboxes = pgTable('poc_sandboxes', {
  id: uuid('id').primaryKey().defaultRandom(),
  pocRunId: uuid('poc_run_id').notNull().unique().references(() => pocRuns.id, { onDelete: 'cascade' }),
  containerId: text('container_id').notNull(),
  runtime: text('runtime').notNull().default('docker'),
  cpuLimit: text('cpu_limit').notNull().default('1.0'),
  memoryLimit: text('memory_limit').notNull().default('1Gi'),
  networkMode: text('network_mode').notNull().default('none'),
  status: text('status').notNull().default('pending'),
  startedAt: timestamp('started_at', { withTimezone: true }),
  destroyedAt: timestamp('destroyed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const pocLibrary = pgTable('poc_library', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  title: text('title').notNull(),
  description: text('description'),
  cweIds: jsonb('cwe_ids').notNull().default([]),
  frameworkTags: jsonb('framework_tags').notNull().default([]),
  language: text('language'),
  pocScript: text('poc_script').notNull(),
  pocScriptHash: text('poc_script_hash').notNull(),
  reuseCount: integer('reuse_count').notNull().default(0),
  lastReusedAt: timestamp('last_reused_at', { withTimezone: true }),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const exploitChains = pgTable('exploit_chains', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  projectId: uuid('project_id').notNull().references(() => projects.id),
  name: text('name').notNull(),
  description: text('description'),
  chainNodes: jsonb('chain_nodes').notNull(),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const pocChatMessages = pgTable('poc_chat_messages', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull(),
  projectId: uuid('project_id').notNull().references(() => projects.id),
  pocRunId: uuid('poc_run_id').references(() => pocRuns.id, { onDelete: 'cascade' }),
  findingId: uuid('finding_id').references(() => findings.id),
  threadId: uuid('thread_id').notNull(),
  parentMessageId: uuid('parent_message_id'),
  role: text('role').notNull(),
  content: text('content').notNull(),
  contentRedacted: boolean('content_redacted').notNull().default(false),
  promptTokens: integer('prompt_tokens').notNull().default(0),
  completionTokens: integer('completion_tokens').notNull().default(0),
  model: text('model'),
  latencyMs: integer('latency_ms'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
});

export const usageEvents = pgTable('usage_events', {
  id: uuid('id'),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id'),
  projectId: uuid('project_id').references(() => projects.id),
  findingId: uuid('finding_id').references(() => findings.id),
  pocRunId: uuid('poc_run_id').references(() => pocRuns.id),
  capability: text('capability').notNull(),
  provider: text('provider').notNull(),
  model: text('model').notNull(),
  promptTokens: integer('prompt_tokens').notNull().default(0),
  completionTokens: integer('completion_tokens').notNull().default(0),
  totalTokens: integer('total_tokens').notNull().default(0),
  costUsd: text('cost_usd').notNull().default('0'),
  requestId: text('request_id'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
});

export const quotaPolicies = pgTable('quota_policies', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  capability: text('capability').notNull(),
  monthlyTokenLimit: text('monthly_token_limit'),
  dailyTokenLimit: text('daily_token_limit'),
  perCallTokenLimit: text('per_call_token_limit'),
  enabled: boolean('enabled').notNull().default(true),
  effectiveFrom: timestamp('effective_from', { withTimezone: true }).notNull(),
  effectiveTo: timestamp('effective_to', { withTimezone: true }),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const quotaAlerts = pgTable('quota_alerts', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  capability: text('capability'),
  alertLevel: text('alert_level').notNull(),
  periodStart: timestamp('period_start', { withTimezone: true }).notNull(),
  usedTokens: text('used_tokens').notNull(),
  limitTokens: text('limit_tokens').notNull(),
  notificationSent: boolean('notification_sent').notNull().default(false),
  notificationChannels: jsonb('notification_channels').notNull().default([]),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
});

export const billingAccounts = pgTable('billing_accounts', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  customerId: uuid('customer_id').notNull().unique().references(() => customers.id),
  plan: text('plan').notNull().default('starter'),
  monthlyTokenQuota: text('monthly_token_quota').notNull().default('100000'),
  overageRateUsdPer1k: text('overage_rate_usd_per_1k').notNull().default('0.020'),
  balanceUsd: text('balance_usd').notNull().default('0'),
  currency: text('currency').notNull().default('USD'),
  status: text('status').notNull().default('active'),
  currentPeriodStart: timestamp('current_period_start', { withTimezone: true }).notNull(),
  currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }).notNull(),
  autoRenew: boolean('auto_renew').notNull().default(true),
  paymentMethodId: text('payment_method_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const plans = pgTable('plans', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: text('code').notNull().unique(),
  displayName: text('display_name').notNull(),
  description: text('description'),
  monthlyTokenQuota: text('monthly_token_quota'),
  monthlyCustomerLimit: integer('monthly_customer_limit'),
  monthlyProjectLimit: integer('monthly_project_limit'),
  overageRateUsdPer1k: text('overage_rate_usd_per_1k').notNull().default('0.020'),
  priceUsd: text('price_usd').notNull().default('0'),
  currency: text('currency').notNull().default('USD'),
  billingPeriod: text('billing_period').notNull().default('monthly'),
  features: jsonb('features').notNull().default({}),
  status: text('status').notNull().default('active'),
  effectiveFrom: timestamp('effective_from', { withTimezone: true }).notNull(),
  effectiveTo: timestamp('effective_to', { withTimezone: true }),
  isPublic: boolean('is_public').notNull().default(true),
  displayOrder: integer('display_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const allocationRules = pgTable('allocation_rules', {
  id: uuid('id').primaryKey().defaultRandom(),
  billingAccountId: uuid('billing_account_id').notNull().references(() => billingAccounts.id),
  strategy: text('strategy').notNull(),
  flatAmountUsd: text('flat_amount_usd'),
  customMultiplier: text('custom_multiplier').notNull().default('1.000'),
  effectiveFrom: timestamp('effective_from', { withTimezone: true }).notNull(),
  effectiveTo: timestamp('effective_to', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const invoices = pgTable('invoices', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  billingAccountId: uuid('billing_account_id').notNull().references(() => billingAccounts.id),
  invoiceNumber: text('invoice_number').notNull().unique(),
  periodStart: timestamp('period_start', { withTimezone: true }).notNull(),
  periodEnd: timestamp('period_end', { withTimezone: true }).notNull(),
  subtotalUsd: text('subtotal_usd').notNull(),
  taxUsd: text('tax_usd').notNull().default('0'),
  totalUsd: text('total_usd').notNull(),
  status: text('status').notNull().default('draft'),
  issuedAt: timestamp('issued_at', { withTimezone: true }),
  dueAt: timestamp('due_at', { withTimezone: true }),
  paidAt: timestamp('paid_at', { withTimezone: true }),
  pdfObjectKey: text('pdf_object_key'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const invoiceLineItems = pgTable('invoice_line_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  invoiceId: uuid('invoice_id').notNull().references(() => invoices.id, { onDelete: 'cascade' }),
  description: text('description').notNull(),
  capability: text('capability'),
  quantity: text('quantity').notNull(),
  unitPriceUsd: text('unit_price_usd').notNull(),
  amountUsd: text('amount_usd').notNull(),
  usageEventIds: jsonb('usage_event_ids').notNull().default([]),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const auditLogs = pgTable('audit_logs', {
  id: uuid('id'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  tenantId: uuid('tenant_id'),
  customerId: uuid('customer_id'),
  actorUserId: uuid('actor_user_id'),
  actorEmail: text('actor_email'),
  actorIp: inet('actor_ip'),
  actorUserAgent: text('actor_user_agent'),
  eventType: text('event_type').notNull(),
  resourceType: text('resource_type'),
  resourceId: uuid('resource_id'),
  action: text('action').notNull(),
  requestId: text('request_id'),
  beforeState: jsonb('before_state'),
  afterState: jsonb('after_state'),
  metadata: jsonb('metadata').notNull().default({}),
  prevHash: text('prev_hash').notNull(),
  entryHash: text('entry_hash').notNull(),
});

export const notifications = pgTable('notifications', {
  id: uuid('id'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  tenantId: uuid('tenant_id').notNull(),
  recipientUserId: uuid('recipient_user_id').notNull().references(() => users.id),
  type: text('type').notNull(),
  title: text('title').notNull(),
  body: text('body'),
  linkUrl: text('link_url'),
  payload: jsonb('payload').notNull().default({}),
  readAt: timestamp('read_at', { withTimezone: true }),
});

export const webhooks = pgTable('webhooks', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  customerId: uuid('customer_id').references(() => customers.id),
  url: text('url').notNull(),
  secretCiphertext: text('secret_ciphertext').notNull(),
  eventTypes: jsonb('event_types').notNull().default([]),
  enabled: boolean('enabled').notNull().default(true),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const webhookDeliveries = pgTable('webhook_deliveries', {
  id: uuid('id').primaryKey().defaultRandom(),
  webhookId: uuid('webhook_id').notNull().references(() => webhooks.id, { onDelete: 'cascade' }),
  eventType: text('event_type').notNull(),
  payload: jsonb('payload').notNull(),
  attempt: integer('attempt').notNull().default(1),
  status: text('status').notNull().default('pending'),
  httpStatus: integer('http_status'),
  responseBody: text('response_body'),
  durationMs: integer('duration_ms'),
  errorMessage: text('error_message'),
  nextRetryAt: timestamp('next_retry_at', { withTimezone: true }),
  deliveredAt: timestamp('delivered_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const reports = pgTable('reports', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  projectId: uuid('project_id').references(() => projects.id),
  findingId: uuid('finding_id').references(() => findings.id),
  reportType: text('report_type').notNull(),
  format: text('format').notNull(),
  periodStart: timestamp('period_start', { withTimezone: true }),
  periodEnd: timestamp('period_end', { withTimezone: true }),
  fileObjectKey: text('file_object_key'),
  fileSizeBytes: text('file_size_bytes'),
  generatedBy: uuid('generated_by').references(() => users.id),
  status: text('status').notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const tenantDataExports = pgTable('tenant_data_exports', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  customerId: uuid('customer_id').references(() => customers.id, { onDelete: 'set null' }),
  requestType: text('request_type').notNull(),
  requestedBy: uuid('requested_by').notNull().references(() => users.id, { onDelete: 'set null' }),
  requestedAt: timestamp('requested_at', { withTimezone: true }).notNull().defaultNow(),
  status: text('status').notNull().default('pending'),
  scope: jsonb('scope').notNull(),
  artifactUri: text('artifact_uri'),
  artifactExpiresAt: timestamp('artifact_expires_at', { withTimezone: true }),
  artifactSha256: text('artifact_sha256'),
  artifactSizeBytes: text('artifact_size_bytes'),
  recordCounts: jsonb('record_counts').notNull().default({}),
  errorMessage: text('error_message'),
  startedAt: timestamp('started_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const scheduledJobs = pgTable('scheduled_jobs', {
  id: uuid('id').primaryKey().defaultRandom(),
  jobType: text('job_type').notNull(),
  queueName: text('queue_name').notNull().default('default'),
  status: text('status').notNull().default('pending'),
  priority: integer('priority').notNull().default(0),
  payload: jsonb('payload').notNull().default({}),
  result: jsonb('result'),
  attempts: integer('attempts').notNull().default(0),
  maxAttempts: integer('max_attempts').notNull().default(3),
  scheduledAt: timestamp('scheduled_at', { withTimezone: true }).notNull().defaultNow(),
  startedAt: timestamp('started_at', { withTimezone: true }),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  durationMs: integer('duration_ms'),
  lockedBy: text('locked_by'),
  lockedUntil: timestamp('locked_until', { withTimezone: true }),
  errorMessage: text('error_message'),
  tenantId: uuid('tenant_id'),
  customerId: uuid('customer_id'),
  projectId: uuid('project_id'),
  correlationId: text('correlation_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const appSettings = pgTable('app_settings', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedBy: uuid('updated_by').references(() => users.id),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const schemaMigrations = pgTable('schema_migrations', {
  version: text('version').primaryKey(),
  description: text('description').notNull(),
  appliedAt: timestamp('applied_at', { withTimezone: true }).notNull().defaultNow(),
  checksum: text('checksum').notNull(),
  rolledBackAt: timestamp('rolled_back_at', { withTimezone: true }),
});
